### ISSUE TITLE
Grüße von Mittelstufe

### ISSUE THREAD

**Issue by Rajhab** [LukH-MC/ITAoberstufe#2]
Wir lieben dich Oberstufe. Grüße geht raus an Aurelio der fake italiener. An Karam der Laptop Gamer und an Daniel mein Kitten

**Comment by Iberuser** [comment]
![th-13287344](https://github.com/LukH-MC/ITAoberstufe/assets/116600993/1d003366-542b-4248-bfda-bb3c6176829b)
